# Netpyne travis testing script

sudo: false

addons:
  apt:
    packages:
       # Requirements for Neuron/NetPyne/OMV
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-tk
    - python-sympy
    - python-tornado
    - python-pandas
    - python-tables 

language: python
python: 2.7

virtualenv:
    system_site_packages: true  

install:
    - pip install scipy
    # Install OMV to facilitate installation of packages below
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    - omv install NEURON
    # Need to pre install pyNeuroML to test export to NeuroML 2
    - omv install pyNeuroML
    # Main install for NetPyNE
    - python setup.py install
    - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/

script:
    # Tutorials
    - cd doc/source/code/
    - $NEURON_HOME/bin/nrnivmodl mod
    - python tut2.py -nogui
    - python tut3.py -nogui
    - python tut5.py -nogui
    - python tut6.py -nogui
    - python tut7.py -nogui
    #- python tut_import.py -nogui  # check why gives error
    # HHTut example
    - cd ../../../examples/HHTut
    - python HHTut_run.py -nogui
    # HybridTut example
    - cd ../HybridTut
    - $NEURON_HOME/bin/nrnivmodl .
    - python HybridTut_run.py -nogui
    # M1 example
    - cd ../M1
    - $NEURON_HOME/bin/nrnivmodl . 
    - python M1_run.py -nogui
    # PTcell example
    - cd ../PTcell
    - $NEURON_HOME/bin/nrnivmodl mod
    - python init.py -nogui
    # LFP recording
    - cd ../LFPrecording
    - $NEURON_HOME/bin/nrnivmodl mod
    - python cell_lfp.py -nogui 
    # - cd ../RL_arm
    # - $NEURON_HOME/bin/nrnivmodl
    # - python main.py
    
    - cd ../..
    # Run all OMV tests...
    - omv all -V


notifications: 
    email: false
    #slack: neurosim:pj4DaRn3CrmH6hSRV0zBhfjS


